name: Auto Pull Request

on:
  push:
    branches-ignore:
      - main
      - master

permissions:
  contents: read
  pull-requests: write

jobs:
  auto-pr:
    name: Create Pull Request
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ github.ref_name }}
          destination_branch: main
          pr_title: ${{ github.ref_name }}
          pr_body: "This PR was automatically created from branch `${{ github.ref_name }}`."
          pr_assignee: ${{ github.actor }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

